# Actions에서 사용되는 이름이다
name: CodeDeploy Sandbox CI

# 특정 트리거가 발생 했을 경우 작업 내용이다.
on:
  #dev 브랜치에 push가 된겨우 실행해라
  #push:
  #branches: [ dev ]
  #master 브랜치에 pull_request가 된겨우 실행해라
  #pull_request:
  #branches: [ master ]

  # 직접 수동 배포를 할 수 있도록 하는 것이다.
  workflow_dispatch:

#특정 셋팅값을 저장해 두기 위한것이다. 주로 s3, codeDeploy, Stage를 사용한다.
env:
  S3_BUCKET_NAME: CodeDeploy-sandbox-code-deploy
  PROJECT_NAME: CodeDeploy
  CODE_DEPLOY_NAME: CodeDeploy
  STAGE: sandbox

# 실제로 동작하는 작업을 의미한다.
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      # 여기 까지가 기본적인 셋팅 값을 의미한다. JDK 버전은 항상 신경써야 한다.

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        shell: bash
      # 해당 폴더에 권한이 없어 작업을 진행을 못 할 수 있기에 권한을 부어해 둔다.

      - name: Build with Gradle
        run: ./gradlew build -x test
        shell: bash
      # 현재 사용자는 gradlew 사용하기 떄문에 먼저 테스트 빌드를 하여서 이상이 없지는 확인작업이다.

      - name: Make zip file
        run: zip -r -j ./$GITHUB_SHA.zip appspec.yml build/libs/*.jar sh/** src/main/resources/*.yml
        shell: bash
      # 실직적으로 필요한 파일들을 따로 분류하여서 zip 파일을 생성한다.
      # $GITHUB_SHA라는 값을 사용하는데 이 값은 Github에서 기본적으로 제공하는 환경변수다.

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.SANDBOX_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SANDBOX_AWS_SECRET_KEY }}
          aws-region: ap-northeast-2
      # AWS파일을 업로드 하기 위해서 사용할 AWS 자격 증명 구성을 해야한다.

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://$S3_BUCKET_NAME/$PROJECT_NAME/$GITHUB_SHA.zip
      # 방금전에 생성한 zip 파일을 s3를 업로드한다.

      - name: Code Deploy
        run: aws deploy create-deployment --application-name $CODE_DEPLOY_NAME --deployment-config-name CodeDeployDefault.AllAtOnce --deployment-group-name $STAGE --s3-location bucket=$S3_BUCKET_NAME,bundleType=zip,key=$PROJECT_NAME/$GITHUB_SHA.zip
